### ISSUE TITLE
implement doBoundingBoxCulling for WarpedSource

### ISSUE THREAD

**Issue by NicoKiaru** [saalfeldlab/bigwarp#105]
Hi @bogovicj, 

I noticed that the doBoundingBoxCulling is not yet implemented in WarpedSource, which leads to 'invisible' sources.

What do you think of implementing it like that ?

```
	public boolean doBoundingBoxCulling()
	{
		return (!isTransformed)&&(source.doBoundingBoxCulling());
	}
```

In fact if the transform is an affine transform, that may be over cautious, as the culling could work. But dealing with special cases may be tricky depending on the transform (maybe it's a wrapped AffineTransform...)

A more flexible alternative could be to have a constructor with a `Supplier<Boolean> doBoundingBoxCulling` and then implement the method like that:

```
	public boolean doBoundingBoxCulling()
	{

                if (doBoundingBoxCulling !=null ) return doBoundingBoxCulling.get();

		return (!isTransformed)&&(source.doBoundingBoxCulling());
	}
```

What do you think ?

**Comment by bogovicj** [comment]
I like your implementation, and I think I'll go with it.

Medium term, I'm going to work on improving the bounding box estimation. The better (more accurate) I make the estimation, the slower it is likely to be, so I likely won't ever have it on by default for purposes of bounding box culling.  Except, maybe, for affine transforms, like you say.  Hopefully a bit of code clean up / simplification will make it handling the special cases not so painful.

**Comment by bogovicj** [comment]
added a `Supplier` so we can customize the behavior in the future

**Comment by NicoKiaru** [comment]
You know what ? Finally I'm wondering where adding a `Supplier` is a good thing... Don't you think extending `WarpedSource` could be a prefereable way to achieve such customization ?

What makes me doubt is the fact that these functional interface (`Supplier<T>` `Function<R,T>`) are not easy to serialize. So I don't know if it's a good practice to use them 'just in case', when there's no current use case...
