### ISSUE TITLE
Respect unit when applying transform

### ISSUE THREAD

**Issue by imagejan** [saalfeldlab/bigwarp#110]
From the presentation at NEUBIAS Academy by @bogovicj:

When applying the transform to the moving image, the spatial calibration is correct, but the unit might get wrong (e.g. `µm` instead of `nm`).

**Comment by bogovicj** [comment]
Thanks @imagejan !

**Comment by bogovicj** [comment]
this is fixed in current master and will be in the next release.  thanks again!

**Comment by imagejan** [comment]
I believe the fix is somewhere in commit https://github.com/saalfeldlab/bigwarp/commit/0fdc77d82041093537c94ff98bbb50a818e67112, right? 🙂
