### ISSUE TITLE
Interpolation/ Smoothing in 3D data

### ISSUE THREAD

**Issue by Theresa-S** [saalfeldlab/bigwarp#111]
Dear John, thanks for the great work you are doing! I'm currently registering MRI and CT data sets onto each other. Unfortunately, they are rotated in random directions along the anterior-posterior axis (image enclosed). When I rotate them to show the exact same plane, there are some strange stripes in the MRI (video enclosed). Is it possible to implement an automated interpolation of some kind to facilitate the landmark identification?

![Big_Warp_Interpolation](https://user-images.githubusercontent.com/61883896/105964441-7d5a0a80-6082-11eb-8d92-71f21f20e421.PNG)

https://user-images.githubusercontent.com/61883896/105964347-58fe2e00-6082-11eb-8a50-b9a78f9fce71.mp4

**Comment by Theresa-S** [comment]
PS: I would be happy to supply you the data for testing.

**Comment by haesleinhuepf** [comment]
Hey @Theresa-S ,

have you tried pressing the "I" key? BugDataViewer should then turn interpolation on/off... 

Cheers,
Robert

**Comment by Theresa-S** [comment]
Yes, that worked... Thank you!
