### ISSUE TITLE
Remember the path

### ISSUE THREAD

**Issue by Theresa-S** [saalfeldlab/bigwarp#113]
I'm not sure if this only interesting for me / if I just didn't find this function:

When opening or saving, is it possible that the dialogue box shows the last used folder and not the root?

**Comment by mattrussellcrick** [comment]
Please please can this be fixed - this certainly happens for me as well

**Comment by bogovicj** [comment]
Agreed, and this is fairly straightforward to do.  
Thanks for reporting.  This will be in the next release.

**Comment by bogovicj** [comment]
This was implemented here aef5c6a41eca12b4c71f34b789106a2a33029f3b, so am closing this issue.
Thanks again for the suggestion.
