### ISSUE TITLE
Can't open .tif files after recent BDV update

### ISSUE THREAD

**Issue by mattrussellcrick** [saalfeldlab/bigwarp#121]
Having just updated Fiji today, I can't open the files I could open before, either with BigWarp, or with Open Current Image. These are .tif stacks.

I have a really old version of java that I didn't get around to updating (that Fiji keeps complaining about when I run updates). Perhaps that's the issue. I've attached some error logs.
[BDV_currentimage1.txt](https://github.com/saalfeldlab/bigwarp/files/6030133/BDV_currentimage1.txt)
[BDV_BigWarp_Exception.txt](https://github.com/saalfeldlab/bigwarp/files/6030134/BDV_BigWarp_Exception.txt)

**Comment by NicoKiaru** [comment]
@mattrussellcrick have you tried removing any extra update site and restarted until you get an 'up to date fiji' ?

I can open an image with 'Open Current Image' but I had to remove a few incompatible update sites for that

**Comment by mattrussellcrick** [comment]
Works after re-installing Fiji

**Comment by mattrussellcrick** [comment]
Works after re-installing Fiji
