### ISSUE TITLE
Settings not loading properly for XML/HDF5 

### ISSUE THREAD

**Issue by mtakeno** [saalfeldlab/bigwarp#123]
I have two XML/HDF5 sources, single channel XYZ volumes each. When I save my settings for a warping visualization session, close BigWarp, then repoen the same volumes and load the same settings file to apply again, the brightness and color settings are not saved and go back to default scales and min/max values... Bookmarks also appear to be lost as well.

Looking at the bigwarp.settings.xml file directly, it appears that the information is being saved in the proper place -- the file appears to reflect value changes made in the UI (e.g. MinMaxGroup, rangeMin and rangeMax) and Bookmarks -- but then do not seem to load properly through the BigWarp UI.

Windows 10; ImageJ 1.53c99; bigwarp_fiji-7.0.1.jar

**Comment by bogovicj** [comment]
@mtakeno 
Thanks for reporting this issue. I was able to reproduce the issue.
Loading settings for xml/hdf5 seems to work correctly after the fix mentioned above.
The next release will have this fix.
