### ISSUE TITLE
Issue loading file

### ISSUE THREAD

**Issue by rentazillla** [saalfeldlab/bigwarp#125]
Hello, this might be a stupid simple fix but I get the following error message when I try to load two images into bigwarp:
`WARNING:
Opening <SpimData> dataset that is not suited for interactive browsing.
Consider resaving as HDF5 for better performance.
WARNING:
Opening <SpimData> dataset that is not suited for interactive browsing.
Consider resaving as HDF5 for better performance.
`

I have tried using both Fiji 1.53 and 1.51 and get the same error. All the necessary updates have been installed. My current Fiji version is is 2.10/1.51w build 5f23140693

**Comment by bogovicj** [comment]
Sorry for the delay @rentazillla ,
This message is just a warning, not an error.  You should be able to safely continue without any problems.

**Comment by bogovicj** [comment]
closing this issue since there's nothing to do.  Please post back here or on https://forum.image.sc/ if you have questions
