### ISSUE TITLE
Add notes or free-form text input field to landmarks

### ISSUE THREAD

**Issue by mtakeno** [saalfeldlab/bigwarp#138]
When placing landmarks, it would be nice to be able to input a note, keyword, or code in a free-form text input field with a particular landmark. E.g. "cell A", "corner point B", "nucleus centroid".

(label: enhancement)

**Comment by bogovicj** [comment]
@mtakeno ,

Clicking in the landmark table let's you change the name of a given landmark.  This is probably appropriate for short-ish text
like your examples.  Does that work for you? or would you like longer descriptions? How and where would you like to input these and / or see the results?

**Comment by mtakeno** [comment]
That works for our purposes, thanks!
