### ISSUE TITLE
Null pointer exception on first install

### ISSUE THREAD

**Issue by NicoKiaru** [saalfeldlab/bigwarp#139]
HI @bogovicj !

I noticed an unusual bug on a Fiji which was just being installed on a machine, and where no file was saved.

This line:
https://github.com/saalfeldlab/bigwarp/blob/8def80a01bcc458231b938bc225cfb7569b7d313/src/main/java/bigwarp/BigWarp.java#L574

Can cause a null pointer exception because `IJ.getDirectory( "current" )` returns null.

Could you modify https://github.com/saalfeldlab/bigwarp/blob/8def80a01bcc458231b938bc225cfb7569b7d313/src/main/java/bigwarp/BigWarp.java#L571 and replace it by

```
if ( ( ij == null )||(IJ.getDirectory( "current" ) == null)) 
```

Thanks!

**Comment by bogovicj** [comment]
Fixed as you suggested, thanks @NicoKiaru !
