### ISSUE TITLE
NPE with ApplyBigWarpPlugin

### ISSUE THREAD

**Issue by NicoKiaru** [saalfeldlab/bigwarp#142]
In this line:
https://github.com/saalfeldlab/bigwarp/blob/4f09a8d8aec50c2fd0cfaf658f66b067c483f753/src/main/java/bdv/ij/ApplyBigwarpPlugin.java#L864

You access a field (writeOpts) which apparently can be null (see condition  above).

**Comment by bogovicj** [comment]
oops, thanks @NicoKiaru !

**Comment by bogovicj** [comment]
should be fixed now. thanks again.
