### ISSUE TITLE
Bigwarp_affinePart.groovy script getAffine() return null pointer

### ISSUE THREAD

**Issue by rintrah** [saalfeldlab/bigwarp#156]
Dear all, 

I need to align some images that I am analyzing with Matlab and Python.  These images are not aligned and I found that Bigwarp is the right tool for this (Thank you!).  Nevertheless, when I use the Bigwarp_affinePart.groovy script I run into the problem that the line 
`affine = ltm.getTransform().getAffine();` returns a null pointer and then the script crashes. 

I wonder whether it would be possible for you to take a look at this particular problem.

Many thanks for considering my request.

**Comment by bogovicj** [comment]
@rintrah 

Thanks for reporting this error.  I've fixed the problem https://github.com/saalfeldlab/bigwarp/commit/491079792fac9fd32ed226c0649d153f8d2febaf

If you get the latest version of the script:
https://github.com/saalfeldlab/bigwarp/blob/master/scripts/Bigwarp_affinePart.groovy
and re-run, then it should work as expected.

Thanks again

**Comment by rintrah** [comment]
Thanks to you for Bigwarp and for taking the time to solve this problem.

Best wishes
