### ISSUE TITLE
Bigwarp Opening files Error

### ISSUE THREAD

**Issue by wikk-chy** [saalfeldlab/bigwarp#169]
Hi, there is something wrong with bigwarp when using the plugin open 2 .tif files in Fiji. I have used the plugin for 2 years while everthing is no problem. I have tried to change the version of Fiji and java, however, it was no use.
Hope for your suggestions and thanks!
![F445F238EA1D1A8EF7EFDF28282E5E96](https://github.com/saalfeldlab/bigwarp/assets/96384394/0107dd67-5f69-48f6-8455-ddda80d836a7)
(Fiji Is Just) ImageJ 2.14.0/1.54f; Java 1.8.0_322 [64-bit]; Windows 10 10.0; 107MB of 5966MB (1%)
 
java.lang.NoClassDefFoundError: net/imglib2/ui/TransformListener
    at bdv.ij.BigWarpImagePlusPlugIn.run(BigWarpImagePlusPlugIn.java:83)
    at ij.IJ.runUserPlugIn(IJ.java:244)
    at ij.IJ.runPlugIn(IJ.java:210)
    at ij.Executer.runCommand(Executer.java:152)
    at ij.Executer.run(Executer.java:70)
    at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.ClassNotFoundException: net.imglib2.ui.TransformListener
    at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
    ... 6 more

**Comment by bogovicj** [comment]
Hi @wikk-chy ,

Thanks for reporting this issue.

* Do you have any update sites enabled on the Fiji installation where you see this error?
* If you download a fresh fiji and update it (without any update sites), do you still see this error?

**Comment by wikk-chy** [comment]
Thank you for your response. 
I have tried version 10.4.3 of bigdataviewer-core.jar and even attempted older versions, but encountered the same error. Interestingly, these versions work on another computer, so I'm unsure what might be causing this discrepancy. Additionally, I downloaded a fresh Fiji installation and attempted to run Bigwarp without any updates, but encountered the same issue. Would you have any insights or suggestions regarding this matter? Thank you.

**Comment by NicoKiaru** [comment]
Not sure it's the issue, but I had a weird issue one time by having two identical jars with different versions in different folders of Fiji (one in `jars` one in `plugins`). Here's the linked thread:

https://forum.image.sc/t/java-lang-nosuchfielderror-disablechromasubsampling-with-ptbiop-update-site/90061/8

**Comment by wikk-chy** [comment]
Thank you for your assistance. I don't think this is an issue with Bigwarp. Please don't close this issue yet. If I manage to resolve the problem, I will reply to you again and close the issue.
