### ISSUE TITLE
NoSuchMethodError upon start of BigWarp

### ISSUE THREAD

**Issue by imagejan** [saalfeldlab/bigwarp#27]
When trying to run BigWarp in an up-to-date Fiji installation using two 16-bit stacks of same size, I get the following exception:

```
java.lang.NoSuchMethodException: Could not find method bdv.tools.brightness.SetupAssignments.<init>(Ljava/util/ArrayList;II)V
There was a problem with the class bdv.tools.brightness.SetupAssignments which can be found here:
/C:/UTILIT~1/Fiji.app/jars/bigdataviewer-core-2.5.1.jar
java.lang.NoSuchMethodError: bdv.tools.brightness.SetupAssignments.<init>(Ljava/util/ArrayList;II)V
	at bigwarp.BigWarp.<init>(BigWarp.java:433)
	at bdv.ij.BigWarpImagePlusPlugIn.run(BigWarpImagePlusPlugIn.java:79)
	at ij.IJ.runUserPlugIn(IJ.java:217)
	at ij.IJ.runPlugIn(IJ.java:181)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at java.lang.Thread.run(Thread.java:745)

	at bigwarp.BigWarp.<init>(BigWarp.java:433)
	at bdv.ij.BigWarpImagePlusPlugIn.run(BigWarpImagePlusPlugIn.java:79)
	at ij.IJ.runUserPlugIn(IJ.java:217)
	at ij.IJ.runPlugIn(IJ.java:181)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at java.lang.Thread.run(Thread.java:745)
```

(Just to be sure: I'm using `bigwarp_fiji-2.1.2.jar` and `bigdataviewer-core-2.5.1.jar`, both served from the Java-8 update site.)

Any ideas?

**Comment by bogovicj** [comment]
Thanks @imagejan,
I did happen to notice that and [fixed it here](https://github.com/saalfeldlab/bigwarp/commit/34c88557e714be8769da5a9d4fe9336a21a1f6d8). As a result, bigwarp 2.1.3 should not have this error.

Unfortunately, I've been [having trouble with the fiji update site](http://forum.imagej.net/t/update-site-upload-attempt-throws-unrelated-dependency-error/3177/17), so bigwarp 2.1.3 isn't in fiji yet :-/

I'm going to leave this issue open until the update site is indeed updated.  Thanks once again for letting us know though!

**Comment by bogovicj** [comment]
[bigwarp-2.1.5 is now on Fiji's Java 8 update site](http://sites.imagej.net/Java-8/plugins/), and resolves this issue.

**Comment by imagejan** [comment]
> bigwarp-2.1.5 is now on Fiji's Java 8 update site

I see it in the file listing, but the updater doesn't seem to be aware of the new file:

![bigwarp-update](https://cloud.githubusercontent.com/assets/2033938/20298087/4fa25f8e-ab14-11e6-8d70-7d13ef1028ca.png)

Any chance that the db.xml.gz wasn't written correctly? Can you try uploading via the Fiji updater once more to see if that's a temporary issue?

**Comment by bogovicj** [comment]
Will look into this, thanks @imagejan

**Comment by bogovicj** [comment]
I replaced the new jar in the old jar in the plugins folder and ran the updater, which seems to know about the update. 

![bw_fiji_updater](https://cloud.githubusercontent.com/assets/6912043/20309110/b36bffc0-ab14-11e6-8fc5-22eb9b5ad75e.png)

Is this issue persisting on your end?

**Comment by imagejan** [comment]
That seems to have fixed the issue. Thanks!
