### ISSUE TITLE
Avoid System.exit calls

### ISSUE THREAD

**Issue by imagejan** [saalfeldlab/bigwarp#3]
I just had a look at BigWarp, it seems to be a great plugin! Still have to get used to the navigation though.
I noticed that when you close the landmarks list window, the whole JVM will be shut down, due to calls to `System.exit`. That way, users will loose all unsaved changes in images and scripts opened in Fiji. It might be enough to just dispose of the `JFrame` and leave the current Fiji/ImageJ instance untouched.

**Comment by bogovicj** [comment]
Good catch, and thanks for the feedback.  I'll make sure that's fixed for the next released.
Ya, the navigation takes a little getting used to.  Personally, I find the 'Q' and 'W' hotkeys
quite useful.

**Comment by bogovicj** [comment]
This is corrected in the current master and will be released soon.
