### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by tferr** [saalfeldlab/bigwarp#32]
Hi @bogovicj!

Finally had a chance to _actually_ play around with BigWarp. Really impressive! I am just opening this to mention a couple of things I noticed while using the UI (on a fresh Fiji installation). Nothing major, nor critical.

- [x] It would be really useful to have an option in the UI to directly save the warped image without having to display it in IJ
- [x] Once exported, warped image seems to loose spatial calibration. Also, on the datasets I tried [8-bit single channel Z-stacks (IJ1 TIFF files)] the Z dimension was swapped with C after export.
- [x] Currently, the title of exported image is a constant string. It would be nice to name the exported image after the input choice. Same for proposed filename when saving landmark files.
- [x] When editing the _Landmarks table_, I was able to delete all landmarks but never the first (Pt-0 in first row). But it could be I missed something...

I could probably look into this, but not immediately though.

**Comment by bogovicj** [comment]
Thanks for the suggestions @tferr.
I'll get right on those - they should all be straightforward to deal with.

**Comment by bogovicj** [comment]
The last issue (deleting the first landmark) was solved here (https://github.com/saalfeldlab/bigwarp/commit/3210aff7770d2e533a0692f6b8cba8fea6acf285), but we just havn't released since then :-/

**Comment by tferr** [comment]
Thanks a lot!! I also noticed that the plugin allows RGB images as input but cannot export them... But I also see that this is addressed in eaa434587d27ffaa7eb01d0aff5d5eb72bef7d65. Great!

**Comment by bogovicj** [comment]
The above are incorporated and are now in a release, so I'm closing this.  Thanks again!
