### ISSUE TITLE
Using Big Warp ImageJ plugin for image registration 

### ISSUE THREAD

**Issue by kikhiam** [saalfeldlab/bigwarp#43]
I am trying to register two stacks of images. Both acquired by a two-photon microscope. The first is for a living hippocampal culture slice and the second is for the same slice after fixation. The fixation results in some distortions in the slice. Therefore, I used Big Warp to register the two images but I didn't know how to start the warping and registration after selecting the landmarks in the two images. 
I think this plugin can solve my problem by I am not applying it correctly. 
Could anyone explain how can I proceed with registration after selecting the landmarks in the two images? 

Thanks

**Comment by axtimwalde** [comment]
Did you read the manual? http://imagej.net/BigWarp

**Comment by kikhiam** [comment]
Yeah of course I did. What I understood is that I need to select the landmarks in both images and then the plugin will align the two images together using the selected landmarks. And you get the result just by exporting the warped image as Virtual ImagePlus or ImagePlus. Is that right? 
Because the warped image I got is very similar to the moving image I have chosen. It seems that no wrapping was done. So I assumed that I misunderstood the instruction in the manual. Are there any steps that I should do other than selecting the landmarks in the two images and exporting the warped image?
Sorry if that is a very basic question.

Thanks for your reply.

**Comment by bogovicj** [comment]
Press "T" after adding landmarks to transform the moving image.

**Comment by kikhiam** [comment]
Thank you so much for your answer. It worked perfectly, at least for fitting the landmark pairs together. I couldn't find this step (Pressing "T" step) in the manual. Could you add it there, since you are the author of the BigWarp?

Thank you for the very cool plugin by the way.

**Comment by bogovicj** [comment]
Yup, my mistake.  I will make that site more clear.

The "T" command *is* documented in the help menu in the tool though.
`F1` or `Help > Show Help Menu`
