### ISSUE TITLE
Affine only transformation 

### ISSUE THREAD

**Issue by david-hoffman** [saalfeldlab/bigwarp#45]
@bogovicj I think it would be useful to have the option to see the affine only transformation. It might also be useful to see the rigid and similarity transformations as well.

**Comment by bogovicj** [comment]
In progress and seems functional but only very roughly tested (https://github.com/saalfeldlab/bigwarp/commit/8a7dd8687717e46b816358915cf63642c0b0ce43).

@david-hoffman, let me know if you'd like to test this out pre-release.

**Comment by bogovicj** [comment]
this new feature is now merged into master
