### ISSUE TITLE
Output deformation field

### ISSUE THREAD

**Issue by david-hoffman** [saalfeldlab/bigwarp#46]
Would it be possible to output the deformation field as well? 

It would be good if this feature were made to be an option because the deformation field for the full resolution volumes will be huge. The deformation field could be output as three separate (for `x`, `y`, and `z` displacements) 32-bit `ImagePlus`s or a single 32-bit multichannel `ImagePlus`.

**Comment by bogovicj** [comment]
Related PR:
https://github.com/imglib/imglib2-realtransform/pull/19

**Comment by bogovicj** [comment]
Added an option to ignore the affine part of the transform for export to deformation field:
https://github.com/saalfeldlab/bigwarp/commit/064619a63428a3369b9dd9356bc395e7177f8d6a
