### ISSUE TITLE
Move to landmark after adding to the moving viewer

### ISSUE THREAD

**Issue by aschampion** [saalfeldlab/bigwarp#54]
When placing a landmark while the moving volume is in transformed mode, once the moving location for a landmark is placed in the moving viewer, the volume transforms immediately but the viewer does not move to keep the landmark location in viewer. This can be disorienting when one wants to place multiple landmarks around a structure, because the landmark location is no longer in view (instead some likely unrelated location in the newly transformed volume).

CC @acardona

**Comment by bogovicj** [comment]
@aschampion thanks for reporting.
CC @acardona

This is tricky. One way I can think  of to "fix" this is to have the camera change positions after every (?) point pair addition.  Though I wonder if this also would be disorienting (in a different way).

Could use of the `W` hotkey be a workaround of sorts here? It will align the moving window to the target viewer and if the corresponding target point is in the target window, then you'll immediately be able to place more points in the same area again.

Let me know what you think.

**Comment by aschampion** [comment]
I think we somehow missed <kbd>W</kbd>/<kbd>Q</kbd>! It seems like those should be enough to do what I wanted. There is still an element of surprise/thinking something has gone wrong when first placing landmarks this way, but with those shortcuts I don't think it would interfere with the workflow.
