### ISSUE TITLE
Right-click does not work in landmark list

### ISSUE THREAD

**Issue by bjtho08** [saalfeldlab/bigwarp#55]
When right-clicking on a landmark in the landmarks list, the expected result is a context menu that gives the possibility of e.g. deleting the landmark in question. However, on Windows, this feature is not available. Right-clicking produces no result at all. Control+left click does not do anything either. Neither does any of the other modifier buttonsa. Selecting a landmark and clicking on the "context menu" button, that some keyboards have, also doesn't do anything. This is with the latest version of BigWarp in FIJI (Not the one shipping with bigdataviewer which is buggy, the latest, 3.1.2)

**Comment by bogovicj** [comment]
Hi @bjtho08 ,
 I can replicate this, thanks for reporting.

**Comment by bogovicj** [comment]
@bjtho08,

Fixed this in 1a8bfc53c2e0031e1ef48a1901f4f30e1b3d68db, and tested on Windows 10, an older macosx (10.10.5), and ubuntu 16.04.

You can grab the latest build [here](http://maven.imagej.net/service/local/repositories/snapshots/content/sc/fiji/bigwarp_fiji/3.1.3-SNAPSHOT/bigwarp_fiji-3.1.3-20190219.152139-5.jar).  I'll give you a chance to test on your setup, and will leave open until the end of the week, or I hear back from you.

Thanks again.

**Comment by bjtho08** [comment]
@bogovicj I can confirm that the latest build fixed the bug on my machine! Thanks a lot for the quick response and fast action 😄
