### ISSUE TITLE
Feature request: warp multi-channel images

### ISSUE THREAD

**Issue by david-hoffman** [saalfeldlab/bigwarp#59]
Would it be possible to warp multi-channel images? right now I have to split the stack, warp each channel individually and then merge them.

**Comment by bogovicj** [comment]
@david-hoffman,

Thanks for the heads up.. Is this an issue with the `Big Warp Apply` "built-in" plugin?

**Comment by david-hoffman** [comment]
Nope (I actually can't figure out how to use `Big Warp Apply` 😳) just from regular `Big Warp`.

It seems to be a bug when the fixed and moving images are not both of the same type, i.e. I can warp a 3 channel 32-bit image to another 3 channel 32-bit image, but not to a single channel 8 bit image. I haven't tried other combinations.

**Comment by bogovicj** [comment]
What's the bigwarp version you're using?

**Comment by david-hoffman** [comment]
`bigwarp_fiji-3.1.2.jar`
