### ISSUE TITLE
Space key as modifier does not work on my desktop

### ISSUE THREAD

**Issue by axtimwalde** [saalfeldlab/bigwarp#6]
It switches on and off immediately, holding the key does so in rapid repetition.

**Comment by bogovicj** [comment]
You're running inside of Fiji I assume?

**Comment by axtimwalde** [comment]
Yes.

**Comment by bogovicj** [comment]
I think it's that 

    new RepeatingReleasedEventsFixer().install();

has to be called early.  And something in Fiji prevents this from having the desired
effect when its called in a script.

I had an ugly hack earlier to make this work before.  It was just a dummy class
that started an ImageJ instance but called the above first.  I'll look into finding a better solution.

**Comment by axtimwalde** [comment]
You could may be run it at class loading time:

{
	new RepeatingReleasedEventsFixer().install();
}

outside of the class?
>

**Comment by bogovicj** [comment]
Corrected in a8f9823160a273153f95664a187534ee511536dc
