### ISSUE TITLE
Exporting the warp field

### ISSUE THREAD

**Issue by zmiller22** [saalfeldlab/bigwarp#69]
I am wondering if there is any way to export just the warp field generated by my landmarks. Every time I use the menu to go file>export warp field my CPU usage goes up for a few seconds and then back down but no new file comes out. Also, afterwards it seems like the BigWarp tool is frozen as it is unresponsive until I force FIJI to restart. Any ideas?

**Comment by bogovicj** [comment]
@zmiller22 ,Thanks for reporting the issue. 

What version of bigwarp are you using?  And do any messages or errors appear in the console?

**Comment by bogovicj** [comment]
A couple more questions - 
1) Are you images 2d or 3d?
2) How large are they?

with bigwarp 5.0.0, I get an error when trying to generate a warp field from landmarks I placed on 2d images, but so far I havn't been able to get bigwarp to freeze as you observed.
```
Exception in thread "Run$_AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: 3
	at net.imglib2.view.Views.permute(Views.java:392)
	at bigwarp.BigWarp.exportWarpField(BigWarp.java:968)
	at bigwarp.BigWarpActions$ExportWarpAction.actionPerformed(BigWarpActions.java:1013)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
...
```

**Comment by zmiller22** [comment]
Hey sorry for the late reply. To answer your question, I am using two fairly large 3d image stacks (a little over one gigabyte each) with around 800 landmarks. Also, no errors were popping up on the console. I just updated this morning and am retrying. So far it seems like it is working after the commit. I will keep you updated.

**Comment by zmiller22** [comment]
Yup, works now. Thank you!
