### ISSUE TITLE
Keyboard shortcut bugs?

### ISSUE THREAD

**Issue by tischi** [saalfeldlab/bigwarp#76]
In the code (`BigWarpActions.java`) it says:
```
		map.put( EXPORT_IP, "control E" );
		map.put( SAVE_WARPED, "control alt shift E" );
```
But in the help (`BigWarpHelp.html`) it says
```
</tr><tr>
  <td class="a"><b>Ctrl&nbsp;E</b></td>
  <td>Export moving image as an ImagePlus</td>
</tr>
<tr>
  <td class="a"><b>Ctrl-Shift&nbsp;E</b></td>
  <td>Export moving image as a virtual ImagePlus</td>
</tr>
<tr>
  <td class="a"><b>Ctrl-Alt&nbsp;E</b></td>
  <td>Save warped moving image to file</td>
</tr>
```
This does not seem to match...

**Comment by tischi** [comment]
@bogovicj 
In principle I am ready to stage a PR for saving the transformation as an xml, however I do not know which keyboard shortcut I could assign to it,  because of the issue above. Could you maybe clean up the shortcuts?

**Comment by bogovicj** [comment]
>  Could you maybe clean up the shortcuts?

Shortcuts fixed.  More comments on the other issue

**Comment by tischi** [comment]
I think it is still not quite right... 

```
map.put( SAVE_WARPED, "control alt shift E" );
```
is now missing completely from the help...

also I do not quite get what the difference between those two is in terms of functionality:
```
		map.put( EXPORT_IP, "control E" );
		map.put( SAVE_WARPED, "control alt shift E" );
```

**Comment by bogovicj** [comment]
I'm not supporting the second option anymore, I should remove it from the action map.
