### ISSUE TITLE
Create xml export for warped image

### ISSUE THREAD

**Issue by tischi** [saalfeldlab/bigwarp#77]
Hi @bogovicj,

I am implementing an export for the warped image in case it was loaded as an XML/H5.
The idea being to simply write a new xml with the BigWarp transform concatenated. 
I will, for now, omit the thin plate spline transform, because I think this is not within the normal specs of the XML/H5 and would thus fail to open in BDV. It would be however very cool to add this later!

I have a first question: How do I get the current transform as an `AffineTransform3D`? I found code like below, but I don't know how to proceed...
```
final InvertibleCoordinateTransform transform = ( ( WrappedCoordinateTransform ) currentTransform ).ct_inv;
```
Can I somehow convert this to an `AffineTransform3D`?

**Comment by bogovicj** [comment]
Steal [this code](https://github.com/saalfeldlab/bigwarp/blob/master/scripts/Apply_Bigwarp_Xfm_csvPts.groovy#L25-L53).

Then each of those classes should have a `toArray(double[])` method.
Might have to take care to check if they're 2d or 3d...

**Comment by bogovicj** [comment]
Regarding shortcuts for this.

For shortcuts, I like `Ctrl-Shift-E` (like export, but different).
`Ctrl - X` (think xml) is o-k too, but I prefer the above b/c this is too similar to the rotation shortcuts.

**Comment by bogovicj** [comment]
#79 adds this feature
