### ISSUE TITLE
Avoid null pointer exception in WarpMagnitudeSource when no voxel dimension exists

### ISSUE THREAD

**Issue by NicoKiaru** [saalfeldlab/bigwarp#83]
When a source has no voxel dimension, `getVoxelDimensions()` returns null. Thus I get a nullpointer exception in the line linked below. Could this be checked and avoided ? Thanks!

https://github.com/saalfeldlab/bigwarp/blob/fd3531fc29118e4763bb34de39ed8be7ea07841f/src/main/java/bigwarp/source/WarpMagnitudeSource.java#L54

**Comment by bogovicj** [comment]
Thanks @NicoKiaru , will check it out

**Comment by bogovicj** [comment]
Related:
https://github.com/bigdataviewer/bigdataviewer-vistools/issues/42

**Comment by NicoKiaru** [comment]
Is this issue still active ? This exception did not occur in a long time now. Can I/ you close it?

**Comment by bogovicj** [comment]
I also have not seen it in a long time, and it should be fixed since the bdv-vistools issue above is closed.
So I think you're right, time to close :)
