### ISSUE TITLE
selection of transformation type in FIJI/ImageJ macro

### ISSUE THREAD

**Issue by jzINKA** [saalfeldlab/bigwarp#93]
Is there a way to set the BigWarp transformation type to 'affine' or 'similarity' using the 'BigWarp apply' method in FIJI macro?
I just want to apply one transformation to several images located in a folder, see my FIJI/ImageJ macro below:

```
input = "D:/ImageFolder";
output = "D:/outputImages/";
setBatchMode(true); 
list = getFileList(input);
for (i = 0; i < list.length; i++){
        action(input, output, list[i]);
}
function action(input, output, filename) {
        run("Big Warp Apply", "landmarks_image_file=[D:/landmarks.csv] moving_image_file=["+input+"/"+filename+"] target_space_file=[D:/target.jpg] resolution=Target field=Target point=[] x=1.0000 y=1.0000 z=1.0000 x_0=0.0000 y_0=0.0000 z_0=0.0000 x_1=-1 y_1=-1 z_1=-1 interpolation=Linear threads=4");
        saveAs("PNG", output + filename);
        close();
}
setBatchMode(false);
```

**Comment by bogovicj** [comment]
I'll have a look, thanks for posting the issue.

**Comment by bogovicj** [comment]
started work on this feature here:
https://github.com/saalfeldlab/bigwarp/tree/applyTransformType

seems functional, but needs more testing

**Comment by jo-mueller** [comment]
Which of the scripts allows to select the transformation type for the transformation of whole images? I've only found a script that transformations csv-list of coordinates with arbitrary transformations.

**Comment by bogovicj** [comment]
@jo-mueller , you'll be able to transform whole images with arbitrary transform types after the next release, coming very soon.

The apply transform plugin now includes transform type selection.
As a result, macros after the next release will include transform type selection.

see https://github.com/saalfeldlab/bigwarp/commit/352f4264b169ffc3fcf2d6025c028cdc19b54994
