### ISSUE TITLE
NullPointerException when initialising BigWarp with SourceAndConverters + ConverterSetups

### ISSUE THREAD

**Issue by NicoKiaru** [saalfeldlab/bigwarp#95]
Hi @bogovicj , 

Before the version `6.0.1-SNAPSHOT` I was capable of starting BigWarp with pairs of `SourceAndConverter` + `ConverterSetup`.

That's useful if the sources are already opened in a Bdv window and you want to reuse them in BigWarp.
I was doing it by calling:
```
BigWarp.BigWarpData bigwarpData = new BigWarp.BigWarpData(sources, converterSetups, new CacheControl.Dummy(), new int[]{0}, new int[]{1} );
BigWarp bigWarp = new BigWarp(bigwarpData, "Big Warp Window", null);        
```
This worked before, but with the new version that includes the transformation computation fix, I get this error:
```
Exception in thread "main" java.lang.NullPointerException
	at bigwarp.BigWarp$BigWarpData.transferChannelSettings(BigWarp.java:2815)
	at bigwarp.BigWarp.<init>(BigWarp.java:544)
	at bigwarp.BigWarp.<init>(BigWarp.java:317)
	at bigwarp.TestInitialisationWithConverterSetups.main(TestInitialisationWithConverterSetups.java:58)
```

Is there a way to solve this ?

I wrote a minimal example that reproduces the error in :

https://github.com/NicoKiaru/bigwarp/blob/4dfd2edf5ef7d479f9fd7f138d0061cb32b17d4f/src/test/java/bigwarp/TestInitialisationWithConverterSetups.java 

Maybe there are alternatives to this  initialization ? Happy to hear about them.

Nico

**Comment by bogovicj** [comment]
Hmm, not sure, will look into this soon.
Thanks for letting me know.

**Comment by bogovicj** [comment]
This should be fixed now.  Thanks for the example as always, that really helps :)

**Comment by NicoKiaru** [comment]
Awesome! Back in business with BigWarp
