### ISSUE TITLE
Issues with opening the Transform Type select window

### ISSUE THREAD

**Issue by MTLucht** [saalfeldlab/bigwarp#96]
Hello,

I am fairly new user of BigWarp. It has worked nicely so far, however, since the latest update I cannot seem to open the "Transform Type Select" window by pressing F8 anymore. Reverting to 5.0.0 seems to resolve the issue for now, but of course a more permanent fix or workaround would be appreciated.

Version with the error: 6.0.0

Please let me know if you need any additional information, plugin versions and so on. I tested the 6.0.1 snapshot as well, but without any change.

**Comment by bogovicj** [comment]
@MTLucht, I can reproduce this issue.  Thanks for reporting.

**Comment by bogovicj** [comment]
The commit above should address this, though "fixing" means moving the keyboard shortcut to `F2`. 
The deprecated visibility and grouping shortcuts also needed to be moved: to `F3` and `F4` respectively.
This fix is available in [bigwarp-6.0.1-SNAPSHOT](https://maven.scijava.org/service/local/repositories/snapshots/content/sc/fiji/bigwarp_fiji/6.0.1-SNAPSHOT/bigwarp_fiji-6.0.1-20200807.153941-7.jar) Could you give that a try?

I don't yet know why `F8` stopped working, will try to look into it.

**Comment by MTLucht** [comment]
It works beautifully. Thanks a lot for your quick help!
