### ISSUE TITLE
F8 does not work

### ISSUE THREAD

**Issue by tischi** [saalfeldlab/bigwarp#98]
@bogovicj 
In the latest Fiji the `F8` key does not work for me. Nothing happens, but it should show a dialog for selecting the transformation model.

**Comment by bogovicj** [comment]
Hi @tischi ,

Thanks for reporting, this was found and fixed here:
https://github.com/saalfeldlab/bigwarp/issues/96

the latest snapshot moves that functionality to `F2`
I wish I knew why F8 in particular is broken but just dont have the time to dig right now :(

**Comment by tischi** [comment]
> the latest snapshot moves that functionality to F2

Do you know when this will become available in Fiji?

**Comment by bogovicj** [comment]
I'll make a release and push it to fiji.  
If not today, then tomorrow, thanks for poking :point_right:

**Comment by bogovicj** [comment]
`bigwarp_fiji-6.0.2` is released, but I was having issues updating Fiji yesterday.

**Comment by K-Meech** [comment]
Hi @bogovicj - is there any update to this issue? I also need to switch the transformation model, but neither F2 or F8 works for me in the current fiji. Thanks!

**Comment by bogovicj** [comment]
Thanks for poking, and your patience.  This was more of a pain than I expected back in Aug, and I let it go :-/ 
Back at it now.

If you're desperate for a workaround right now, you can manually install  [bigwarp-6.0.2](https://maven.scijava.org/service/local/repositories/releases/content/sc/fiji/bigwarp_fiji/6.0.2/bigwarp_fiji-6.0.2.jar) into your fiji and it should fix this issue.
